// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a stub file - run `make proto` to generate actual protobuf code

package pb

import (
	"context"
	"google.golang.org/protobuf/types/known/structpb"
)

// Stub definitions for proto messages
type RetrieveRequest struct {
	N       int32     `json:"n"`
	Type    *string   `json:"type,omitempty"`
	Queries []string  `json:"queries"`
}

type RetrieveResponse struct {
	Rules []*RuleMatch `json:"rules"`
}

type RuleMatch struct {
	Id        int64              `json:"id"`
	Type      string             `json:"type"`
	Content   *structpb.Struct   `json:"content"`
	Score     float64            `json:"score"`
	CreatedAt string             `json:"created_at"`
	UpdatedAt string             `json:"updated_at"`
}

// Stub for gRPC service interface
type RuleRetrievalServiceServer interface {
	Retrieve(context.Context, *RetrieveRequest) (*RetrieveResponse, error)
}

// Stub for unimplemented server
type UnimplementedRuleRetrievalServiceServer struct{}

func (UnimplementedRuleRetrievalServiceServer) Retrieve(context.Context, *RetrieveRequest) (*RetrieveResponse, error) {
	return nil, nil
}

// Stub for client interface
type RuleRetrievalServiceClient interface {
	Retrieve(ctx context.Context, in *RetrieveRequest) (*RetrieveResponse, error)
}